name: root
channels: !!python/tuple
- defaults
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::bleach=1.5.0=py35_0
- conda-forge::decorator=4.0.11=py35_0
- conda-forge::entrypoints=0.2.2=py35_1
- conda-forge::fontconfig=2.12.1=4
- conda-forge::freetype=2.7=1
- conda-forge::gmp=6.1.2=0
- conda-forge::html5lib=0.999=py35_0
- conda-forge::icu=58.1=1
- conda-forge::ipykernel=4.5.2=py35_0
- conda-forge::ipython=5.3.0=py35_0
- conda-forge::ipython_genutils=0.1.0=py35_0
- conda-forge::jinja2=2.9.5=py35_0
- conda-forge::jsonschema=2.5.1=py35_0
- conda-forge::jupyter_client=5.0.0=py35_0
- conda-forge::jupyter_core=4.3.0=py35_0
- conda-forge::libpng=1.6.28=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::markupsafe=0.23=py35_1
- conda-forge::matplotlib=2.0.0=np112py35_2
- conda-forge::mistune=0.7.3=py35_1
- conda-forge::nbconvert=5.1.1=py35_0
- conda-forge::nbformat=4.2.0=py35_0
- conda-forge::notebook=4.4.1=py35_0
- conda-forge::numpy=1.12.0=py35_blas_openblas_200
- conda-forge::openblas=0.2.19=1
- conda-forge::pandas=0.19.2=np112py35_1
- conda-forge::pandoc=1.19.2=0
- conda-forge::pandocfilters=1.4.1=py35_0
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::prompt_toolkit=1.0.13=py35_0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pygments=2.2.0=py35_0
- conda-forge::pyqt=4.11.4=py35_2
- conda-forge::pyzmq=16.0.2=py35_1
- conda-forge::scipy=0.18.1=np112py35_blas_openblas_201
- conda-forge::seaborn=0.7.1=py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::terminado=0.6=py35_0
- conda-forge::testpath=0.3=py35_0
- conda-forge::tornado=4.4.2=py35_0
- conda-forge::traitlets=4.3.1=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::webencodings=0.5=py35_0
- conda-forge::xlrd=1.0.0=py35_1
- conda-forge::zeromq=4.2.1=1
- beautifulsoup4=4.5.3=py35_0
- cycler=0.10.0=py35_0
- dbus=1.10.10=0
- expat=2.1.0=0
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- lxml=3.7.3=py35_0
- mkl=2017.0.1=0
- openssl=1.0.2k=1
- pcre=8.39=1
- pip=9.0.1=py35_1
- pyparsing=2.1.4=py35_0
- python=3.5.0=1
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- pyyaml=3.12=py35_0
- qt=4.8.7=3
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3

